services:
  - type: web
    name: pm-internship-backend
    env: docker
    dockerContext: ./pm_internship_backend
    dockerfilePath: ./pm_internship_backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
